//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using CompositeControl.Areas.CompositeControl.Models;

namespace CompositeControl.Areas.CompositeControl.Views.Shared.DisplayTemplates
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/CompositeControl/Views/Shared/DisplayTemplates/IAgentPart.cshtml")]
	public class _Page_Areas_CompositeControl_Views_Shared_DisplayTemplates_IAgentPart_cshtml : WebViewPage<AgentPartModel>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get
			{
				return ((Context.ApplicationInstance));
			}
		}

		public override void Execute()
		{
			WriteLiteral("\r\n\r\n");

			Write(Model.Part.DescriptiveName);

			WriteLiteral("\r\n(<a href=\"");

			Write(
				Url.Action(
					"ViewPartCollection",
					"Agents",
					new { agentSystemName = @Model.AgentSystemName, descriptiveName = @Model.Part.DescriptiveName }));

			WriteLiteral("\">html</a> |\r\n<a href=\"");

			Write(
				Url.Action(
					"ViewPartCollection",
					"Agents",
					new { agentSystemName = @Model.AgentSystemName, descriptiveName = @Model.Part.DescriptiveName, format = "xml" }));

			WriteLiteral("\">xml</a> |\r\n<a href=\"");

			Write(
				Url.Action(
					"ViewPartCollection",
					"Agents",
					new { agentSystemName = @Model.AgentSystemName, descriptiveName = @Model.Part.DescriptiveName, format = "json" }));

			WriteLiteral("\">json</a>)\r\n<ul>\r\n");

			foreach (var p in @Model.Part.Collection)
			{
				WriteLiteral("\t\t<li id=\"");

				Write(Model.AgentSystemName);

				WriteLiteral("-");

				Write(Model.Part.CollectionType.Name.ToLower());

				WriteLiteral("\">\r\n\t\t\t");

				Write(p.Namespace);

				WriteLiteral(".");

				Write(p.Name);

				WriteLiteral("\r\n\t\t\t(<a href=\"");

				Write(Url.Action(@Model.NextAction, "Agents", new { agentSystemName = @Model.AgentSystemName, partName = p.Name }));

				WriteLiteral("\">html</a> |\r\n\t\t\t<a href=\"");

				Write(
					Url.Action(
						@Model.NextAction, "Agents", new { agentSystemName = @Model.AgentSystemName, partName = p.Name, format = "xml" }));

				WriteLiteral("\">xml</a> |\r\n\t\t\t<a href=\"");

				Write(
					Url.Action(
						@Model.NextAction, "Agents", new { agentSystemName = @Model.AgentSystemName, partName = p.Name, format = "json" }));

				WriteLiteral("\">json</a>)\r\n\r\n\t\t</li>\r\n");
			}

			WriteLiteral("</ul>");
		}
	}
}