//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Euclid.Framework.AgentMetadata;

namespace AgentPanel.Areas.Metadata.Views.Shared.DisplayTemplates
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/Metadata/Views/Shared/DisplayTemplates/IAgentMetadata.cshtml")]
	public class _Page_Areas_Metadata_Views_Shared_DisplayTemplates_IAgentMetadata_cshtml : WebViewPage<IAgentMetadata>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get { return (Context.ApplicationInstance); }
		}

		public override void Execute()
		{
			WriteLiteral("\r\n<fieldset>\r\n    <legend>");


			Write(Model.SystemName);

			WriteLiteral(" Metadata</legend>\r\n    \r\n\r\n</fieldset>\r\n");
		}
	}
}
