//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using CompositeControl.Areas.CompositeControl.Models;

namespace CompositeControl.Areas.CompositeControl.Views.Agents
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/CompositeControl/Views/Agents/Index.cshtml")]
	public class _Page_Areas_CompositeControl_Views_Agents_Index_cshtml : WebViewPage<AgentListModel>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get
			{
				return ((Context.ApplicationInstance));
			}
		}

		public override void Execute()
		{
			WriteLiteral(
				"\r\n<h1>Configured Agents</h1>\r\n\r\n<p>The following agents have been configured in y"
				+ "our composite.</p>\r\n\r\n<ul>\r\n");

			foreach (var agent in Model.Agents)
			{
				WriteLiteral("\t\t<li>\r\n\t\t\t");

				Write(agent.DescriptiveName);

				WriteLiteral(" - ");

				Write(agent.SystemName);

				WriteLiteral(" \r\n\t\t\t(<a href=\"");

				Write(Url.Action("ViewAgent", "Agents", new { agentSystemName = agent.SystemName }));

				WriteLiteral("\">html</a> |\r\n\t\t\t<a href=\"");

				Write(Url.Action("ViewAgent", "Agents", new { agentSystemName = agent.SystemName, Format = "xml" }));

				WriteLiteral("\">xml</a> |\r\n\t\t\t<a href=\"");

				Write(Url.Action("ViewAgent", "Agents", new { agentSystemName = agent.SystemName, Format = "json" }));

				WriteLiteral("\">json</a>)\r\n\t\t</li>\r\n");
			}

			WriteLiteral("</ul>\r\n\r\n");

			Html.RenderPartial("MetadataLinks", Model);
		}
	}
}