//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using CompositeControl.Areas.CompositeControl.Models;

namespace CompositeControl.Areas.CompositeControl.Views.Agents
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/CompositeControl/Views/Agents/ViewAgent.cshtml")]
	public class _Page_Areas_CompositeControl_Views_Agents_ViewAgent_cshtml : WebViewPage<AgentModel>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get
			{
				return ((Context.ApplicationInstance));
			}
		}

		public override void Execute()
		{
			WriteLiteral("\r\n<h1>");

			Write(ViewBag.Title);

			WriteLiteral("</h1>\r\n<p>");

			Write(Model.DescriptiveName);

			WriteLiteral("</p>\r\n<ul>\r\n\t<li>");

			Write(Html.DisplayFor(x => x.Commands, "IAgentPart", @Model.Commands));

			WriteLiteral("</li>\r\n\t<li>");

			Write(Html.DisplayFor(x => x.Queries, "IAgentPart", @Model.Queries));

			WriteLiteral("</li>\r\n\t<li>");

			Write(Html.DisplayFor(x => x.ReadModels, "IAgentPart", @Model.ReadModels));

			WriteLiteral("</li>\r\n</ul>\r\n\r\n");

			Html.RenderPartial("MetadataLinks", Model);
		}
	}
}