//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace AgentPanel.Areas.Metadata.Views.CommandRegistry
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/Metadata/Views/CommandRegistry/Details.cshtml")]
	public class _Page_Areas_Metadata_Views_CommandRegistry_Details_cshtml : WebViewPage<dynamic>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get { return (Context.ApplicationInstance); }
		}

		public override void Execute()
		{
			WriteLiteral("<div>\r\n\tId: ");


			Write(Model.Identifier);

			WriteLiteral("\r\n\t<br />\r\n\tCreated: ");


			Write(Model.Created);

			WriteLiteral("\r\n\t<br />\r\n\tDispatched: ");


			Write(Model.Dispatched);

			WriteLiteral("\r\n\t<br />\r\n\tError: ");


			Write(Model.Error);

			WriteLiteral("\r\n\t<br />\r\n\tMessage: ");


			Write(Model.ErrorMessage);

			WriteLiteral("\r\n\t<br />\r\n\tType: ");


			Write(Model.MessageType);

			WriteLiteral("\r\n\t<br />\r\n\tLocation: ");


			Write(Model.MessageLocation);

			WriteLiteral("\r\n</div>\r\n\r\n");
		}
	}
}
