//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace AgentPanel.Areas.Metadata.Views.Shared
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/Metadata/Views/Shared/_Layout.cshtml")]
	public class _Page_Areas_Metadata_Views_Shared__Layout_cshtml : WebViewPage<dynamic>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get { return (Context.ApplicationInstance); }
		}

		public override void Execute()
		{
			WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n\t<head>\r\n\t\t<title>");


			Write(ViewBag.Title);

			WriteLiteral("</title>\r\n\t\t<link href=\"");


			Write(Url.Content("~/Areas/Metadata/Content/euclid-default-styles.css"));

			WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n\t\t<script src=\"");


			Write(Url.Content("~/Areas/Metadata/Scripts/jquery-1.6.2.min.js"));

			WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t\t<script src=\"");


			Write(Url.Content("~/Areas/Metadata/Scripts/jquery.validate.js"));

			WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t\t<script src=\"");


			Write(Url.Content("~/Areas/Metadata/Scripts/jquery.validate.unobtrusive.js"));

			WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t\t<script src=\"");


			Write(Url.Content("~/Areas/Metadata/Scripts/modernizr-2.0.6-development-only.js"));

			WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t</head>\r\n\r\n\t<body>\r\n\t\t");


			Write(RenderBody());

			WriteLiteral("\r\n\t</body>\r\n</html>\r\n");
		}
	}
}
