//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace AgentPanel.Areas.Metadata.Views.Shared
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/Metadata/Views/Shared/Error.cshtml")]
	public class _Page_Areas_Metadata_Views_Shared_Error_cshtml : WebViewPage<dynamic>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get { return (Context.ApplicationInstance); }
		}

		public override void Execute()
		{
			Layout = null;


			WriteLiteral(
			             "\r\n<!DOCTYPE html>\r\n<html>\r\n\t<head>\r\n\t\t<title>Error</title>\r\n\t</head>\r\n\t<body>\r\n\t\t" +
			             "<h2>\r\n\t\t\tSorry, an error occurred while processing your request.\r\n\t\t</h2>\r\n\t</bo" +
			             "dy>\r\n</html>\r\n");
		}
	}
}
