//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using AgentPanel.Areas.Metadata.Models;

namespace AgentPanel.Areas.Metadata.Views.Shared
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/Metadata/Views/Shared/MetadataLinks.cshtml")]
	public class _Page_Areas_Metadata_Views_Shared_MetadataLinks_cshtml : WebViewPage<FooterLinkModel>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get { return (Context.ApplicationInstance); }
		}

		public override void Execute()
		{
			WriteLiteral("<hr />\r\n\r\n<div class=\"metadata-links-container\" id=\"link-container\">\r\n\t<ul class=" +
			             "\"metadata-links-list\">\r\n");


			if (!string.IsNullOrEmpty(Model.AgentSytemName) && !string.IsNullOrEmpty(Model.PartType))
			{
				WriteLiteral("\t\t\t<li class=\"metadata-link-item\"><a class=\"metadata-link\" href=\"");


				Write(Url.Action("ViewPartCollection", "Agents", 
				                 new {AgentSystemName = Model.AgentSytemName, PartName = Model.PartType}));

				WriteLiteral("\">\r\n\t\t\t\t");


				Write(Model.AgentSytemName);

				WriteLiteral("\'s ");


				Write(Model.PartDescriptiveName);

				WriteLiteral("\r\n\t\t\t</a></li>\r\n");
			}


			if (!string.IsNullOrEmpty(Model.AgentSytemName))
			{
				WriteLiteral("\t\t\t<li class=\"metadata-link-item\"><a class=\"metadata-link\" href=\"");


				Write(Url.Action("ViewAgent", "Agents", new {AgentSystemName = Model.AgentSytemName, }));

				WriteLiteral("\">");


				Write(Model.AgentSytemName);

				WriteLiteral("\r\n\t\t\t\tdetails</a></li>\r\n");
			}

			WriteLiteral("\t\t<li class=\"metadata-link-item\"><a class=\"metadata-link\" href=\"");


			Write(Url.Action("Index", "Agents"));

			WriteLiteral("\">\r\n\t\t\tAgents in composite</a></li>\r\n\t</ul>\r\n</div>\r\n\r\n");
		}
	}
}
