//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentPanel.Areas.Metadata.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    using AgentPanel.Areas.Metadata.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Metadata/Views/Shared/MetadataLinks.cshtml")]
    public class _Page_Areas_Metadata_Views_Shared_MetadataLinks_cshtml : System.Web.Mvc.WebViewPage<FooterLinkModel>
    {
#line hidden

        public _Page_Areas_Metadata_Views_Shared_MetadataLinks_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n<div class=\"metadata-links-container\" id=\"link-container\">\r\n\t<ul class=\"metadat" +
"a-links-list\">\r\n");


 		if (!string.IsNullOrEmpty(Model.AgentSytemName) && !string.IsNullOrEmpty(Model.PartType))
		{

WriteLiteral("\t\t\t<li class=\"metadata-link-item\">\r\n\t\t\t\t<a class=\"metadata-link\" href=\"");


                              Write(Url.Action("ViewPartCollection", "Agents", new {AgentSystemName = Model.AgentSytemName, PartName = Model.PartType}));

WriteLiteral("\">\r\n\t\t\t\t\t");


Write(Model.AgentSytemName);

WriteLiteral("\'s ");


                        Write(Model.PartDescriptiveName);

WriteLiteral("\r\n\t\t\t\t</a>\r\n\t\t\t</li>\r\n");


		}

WriteLiteral("\r\n");


 		if (!string.IsNullOrEmpty(Model.AgentSytemName))
		{

WriteLiteral("\t\t\t<li class=\"metadata-link-item\"><a class=\"metadata-link\" href=\"");


                                                            Write(Url.Action("ViewAgent", "Agents", new {AgentSystemName = Model.AgentSytemName,}));

WriteLiteral("\">");


                                                                                                                                               Write(Model.AgentSytemName);

WriteLiteral(" details</a></li>\r\n");


		}

WriteLiteral("\r\n\t\t<li class=\"metadata-link-item\"><a class=\"metadata-link\" href=\"");


                                                           Write(Url.Action("Index", "Agents"));

WriteLiteral("\">Agents in composite</a></li>\r\n\t</ul>\r\n</div>\r\n");


        }
    }
}
