//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompositeControl.Areas.CompositeControl.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CompositeControl/Views/Shared/_Layout.cshtml")]
    public class _Page_Areas_CompositeControl_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
#line hidden

        public _Page_Areas_CompositeControl_Views_Shared__Layout_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n\t<head>\r\n\t\t<title>");


    Write(ViewBag.Title);

WriteLiteral("</title>\r\n\t\t<link href=\"");


         Write(Url.Content("~/Areas/CompositeControl/Content/euclid-default-styles.css"));

WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n\t\t<script src=\"");


          Write(Url.Content("~/Areas/CompositeControl/Scripts/jquery-1.6.2.min.js"));

WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t\t<script src=\"");


          Write(Url.Content("~/Areas/CompositeControl/Scripts/jquery.validate.js"));

WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t\t<script src=\"");


          Write(Url.Content("~/Areas/CompositeControl/Scripts/jquery.validate.unobtrusive.js"));

WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t\t<script src=\"");


          Write(Url.Content("~/Areas/CompositeControl/Scripts/modernizr-2.0.6-development-only.js"));

WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\t</head>\r\n\r\n\t<body>\r\n\t\t");


Write(RenderBody());

WriteLiteral("\r\n\t</body>\r\n</html>");


        }
    }
}
