//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompositeControl.Areas.Metadata.Views.Agents
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    using AgentPanel.Areas.Metadata.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Metadata/Views/Agents/Index.cshtml")]
    public class _Page_Areas_Metadata_Views_Agents_Index_cshtml : System.Web.Mvc.WebViewPage<AgentListModel>
    {
#line hidden

        public _Page_Areas_Metadata_Views_Agents_Index_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n<h1>Configured Agents</h1>\r\n\r\n<p>The following agents have been configured in y" +
"our composite.</p>\r\n\r\n<ul>\r\n");


     foreach (var agent in Model.Agents)
    {

WriteLiteral("        <li>\r\n            ");


       Write(agent.DescriptiveName);

WriteLiteral(" - ");


                                Write(agent.SystemName);

WriteLiteral(" \r\n            (<a href=\"");


                 Write(Url.Action("ViewAgent", "Agents", new {agentSystemName = agent.SystemName}));

WriteLiteral("\">html</a> |\r\n            <a href=\"");


                Write(Url.Action("ViewAgent", "Agents", new {agentSystemName = agent.SystemName, Format = "xml"}));

WriteLiteral("\">xml</a> |\r\n            <a href=\"");


                Write(Url.Action("ViewAgent", "Agents", new {agentSystemName = agent.SystemName, Format = "json"}));

WriteLiteral("\">json</a>)\r\n        </li>\r\n");


    }

WriteLiteral("</ul>\r\n\r\n");


   Html.RenderPartial("MetadataLinks", Model); 

        }
    }
}
