//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Euclid.Common.Messaging;

namespace CompositeControl.Areas.CompositeControl.Views.CommandRegistry
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/CompositeControl/Views/CommandRegistry/Index.cshtml")]
	public class _Page_Areas_CompositeControl_Views_CommandRegistry_Index_cshtml : WebViewPage<dynamic>
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get
			{
				return ((Context.ApplicationInstance));
			}
		}

		public override void Execute()
		{
			WriteLiteral("\t\t\t\t \r\n<h2>Publication Records</h2>\r\n\r\n");

			foreach (IPublicationRecord pub in Model.PublicationRecords)
			{
				WriteLiteral("\t<div>\r\n\t\tId: <a href=\'");

				Write(Url.Action("Details", "CommandRegistry", new { publicationId = pub.Identifier }));

				WriteLiteral("\'>");

				Write(pub.Identifier);

				WriteLiteral("</a>\r\n\t\t<br />\r\n\t\tCreated: ");

				Write(pub.Created);

				WriteLiteral("\r\n\t\t<br />\r\n\t\tDispatched: ");

				Write(pub.Dispatched);

				WriteLiteral("\r\n\t\t<br />\r\n\t\tError: ");

				Write(pub.Error);

				WriteLiteral("\r\n\t\t<br />\r\n\t\tMessage: ");

				Write(pub.ErrorMessage);

				WriteLiteral("\r\n\t\t<br />\r\n\t\tType: ");

				Write(pub.MessageType);

				WriteLiteral("\r\n\t\t<br />\r\n\t\tLocation: ");

				Write(pub.MessageLocation);

				WriteLiteral("\r\n\t</div>\r\n");

				WriteLiteral("\t<br />\r\n");
			}
		}
	}
}