//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace AgentPanel.Areas.Metadata.Views
{
	[GeneratedCode("MvcRazorClassGenerator", "1.0")]
	[PageVirtualPath("~/Areas/Metadata/Views/_ViewStart.cshtml")]
	public class _Page_Areas_Metadata_Views__ViewStart_cshtml : ViewStartPage
	{
#line hidden

		protected HttpApplication ApplicationInstance
		{
			get { return (Context.ApplicationInstance); }
		}

		public override void Execute()
		{
			Layout = "~/Areas/Metadata/Views/Shared/_Layout.cshtml";
		}
	}
}
